services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: miapidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database-1.cvsvuhbh6kob.us-east-1.rds.amazonaws.com;Database=aztro;Username=postgres;Password=M4_bPT-Hwq8Plf>w>jjm40k3!dt(;

volumes:
  pgdata: